events {}

http {

    upstream user_service {
        server user-service:3001;
    }

    upstream product_service {
        server product-service:3002;
    }

    upstream order_service {
        server order-service:3003;
    }

    upstream payment_service {
        server payment-service:3004;
    }

    upstream notification_service {
        server notification-service:3005;
    }

    server {

        listen 80;

        # Health check
        location /health {
            return 200 "NGINX UP";
        }

        # User Service
        location /users {
            proxy_pass http://user_service;
        }

        # Product Service
        location /products {
            proxy_pass http://product_service;
        }

        # Order Service
        location /orders {
            proxy_pass http://order_service;
        }

        # Payment Service
        location /payments {
            proxy_pass http://payment_service;
        }

        # Notification Service
        location /notifications {
            proxy_pass http://notification_service;
        }
    }
}