events {}

http {

    upstream user_service {
        server user-service:3001;
    }

    upstream product_service {
        server product-service:3002;
    }

    upstream order_service {
        server order-service:3003;
    }

    upstream payment_service {
        server payment-service:3004;
    }

    upstream notification_service {
        server notification-service:3005;
    }

    server {

        listen 80;

        # =========================
        # NGINX HEALTH CHECK
        # =========================

        location = /health {
            return 200 "NGINX UP";
        }


        # =========================
        # USER SERVICE
        # =========================

        location = /users/health {
            proxy_pass http://user_service/health;
        }

        location /users {
            proxy_pass http://user_service;
        }


        # =========================
        # PRODUCT SERVICE
        # =========================

        location = /products/health {
            proxy_pass http://product_service/health;
        }

        location /products {
            proxy_pass http://product_service;
        }


        # =========================
        # ORDER SERVICE
        # =========================

        location = /orders/health {
            proxy_pass http://order_service/health;
        }

        location /orders {
            proxy_pass http://order_service;
        }


        # =========================
        # PAYMENT SERVICE
        # =========================

        location = /payments/health {
            proxy_pass http://payment_service/health;
        }

        location /payments {
            proxy_pass http://payment_service;
        }


        # =========================
        # NOTIFICATION SERVICE
        # =========================

        location = /notifications/health {
            proxy_pass http://notification_service/health;
        }

        location /notifications {
            proxy_pass http://notification_service;
        }
    }
}
